if(NOT DEFINED VF_UI_SOURCE_DIR OR NOT DEFINED VF_UI_OUT_RC OR NOT DEFINED VF_UI_OUT_CPP OR NOT DEFINED VF_UI_OUT_HPP)
  message(FATAL_ERROR "VF_UI_SOURCE_DIR, VF_UI_OUT_RC, VF_UI_OUT_CPP, and VF_UI_OUT_HPP are required")
endif()

get_filename_component(VF_UI_SOURCE_DIR "${VF_UI_SOURCE_DIR}" ABSOLUTE)
if(NOT IS_DIRECTORY "${VF_UI_SOURCE_DIR}")
  message(FATAL_ERROR "source directory not found: ${VF_UI_SOURCE_DIR}")
endif()

set(VF_UI_NATIVE_SCENE_ASSETS
  ".gitignore"
  ".vf-ui-version"
  "index.html"
  "vkf-scene.html"
  "vf-log.js"
  "vf-runtime-shell.js"
  "vf-runtime-packet-contract.js"
  "vf-runtime-source.js"
  "vf-runtime-scene.js"
  "vf-runtime-flow.js"
  "vf-render-clock.js"
  "vf-frame.css"
  "vf-frame.js"
  "vf-widgets.js"
  "vf-axis3d-kernel.js"
  "vf-axis3d-kernel-adapter.js"
  "vf-axis3d-projection-kernel.js"
  "vf-axis3d-projection-kernel-adapter.js"
  "vf-chess.css"
  "vf-display.js"
  "vf-native-scene.js"
  "katex/katex.min.css"
  "katex/katex.min.js"
  "geom/vf-geom-math.js"
  "geom/vf-geom-core.js"
  "geom/vf-geom-ledger-layout.js"
  "geom/vf-geom-ledger-transport.js"
  "geom/vf-geom-ledger.js"
  "geom/vf-geom-parametric-surface.js"
  "geom/vf-geom-material-arena.js"
  "geom/vf-geom-frame-adapter.js"
  "geom/vf-geom-wgpu.js"
  "assets/fonts/NotoSans-Regular-chess-sdf.png"
)

file(GLOB_RECURSE VF_UI_CANDIDATES RELATIVE "${VF_UI_SOURCE_DIR}" "${VF_UI_SOURCE_DIR}/*")
list(SORT VF_UI_CANDIDATES)

set(VF_UI_EMBEDDED_RELS "")
foreach(rel IN LISTS VF_UI_CANDIDATES)
  set(asset_path "${VF_UI_SOURCE_DIR}/${rel}")
  if(IS_DIRECTORY "${asset_path}")
    continue()
  endif()
  if(rel MATCHES "^sessions/")
    continue()
  endif()
  if(rel MATCHES "^katex/fonts/[^/]+$")
    list(APPEND VF_UI_EMBEDDED_RELS "${rel}")
    continue()
  endif()
  if(rel IN_LIST VF_UI_NATIVE_SCENE_ASSETS)
    list(APPEND VF_UI_EMBEDDED_RELS "${rel}")
  endif()
endforeach()

set(version_input "")
foreach(rel IN LISTS VF_UI_EMBEDDED_RELS)
  file(READ "${VF_UI_SOURCE_DIR}/${rel}" asset_hex HEX)
  string(APPEND version_input "${rel}|${asset_hex}|")
endforeach()
string(SHA256 version_hash "${version_input}")
string(SUBSTRING "${version_hash}" 0 24 vf_ui_version)

get_filename_component(out_rc_dir "${VF_UI_OUT_RC}" DIRECTORY)
get_filename_component(out_cpp_dir "${VF_UI_OUT_CPP}" DIRECTORY)
get_filename_component(out_hpp_dir "${VF_UI_OUT_HPP}" DIRECTORY)
file(MAKE_DIRECTORY "${out_rc_dir}" "${out_cpp_dir}" "${out_hpp_dir}")

set(rc_text "// Generated by generate_embedded_vf_ui_assets.cmake; do not edit.\n#include <windows.h>\n\n")
set(base_id 1000)
set(index 0)
foreach(rel IN LISTS VF_UI_EMBEDDED_RELS)
  math(EXPR resource_id "${base_id} + ${index}")
  set(asset_path "${VF_UI_SOURCE_DIR}/${rel}")
  string(REPLACE "\"" "\\\"" rc_path "${asset_path}")
  string(APPEND rc_text "${resource_id} RCDATA \"${rc_path}\"\n")
  math(EXPR index "${index} + 1")
endforeach()
file(WRITE "${VF_UI_OUT_RC}" "${rc_text}")

file(WRITE "${VF_UI_OUT_HPP}" "#pragma once\n#include <cstddef>\n\nstruct VfEmbeddedAsset {\n    int resource_id;\n    const char* relative_path;\n    unsigned long long size;\n};\n\nextern const char* const kVfEmbeddedVfUiVersion;\nextern const VfEmbeddedAsset kVfEmbeddedVfUiAssets[];\nextern const std::size_t kVfEmbeddedVfUiAssetCount;\n")

set(cpp_text "// Generated by generate_embedded_vf_ui_assets.cmake; do not edit.\n#include \"embedded_vf_ui_assets.hpp\"\n\nconst char* const kVfEmbeddedVfUiVersion = \"${vf_ui_version}\";\nconst VfEmbeddedAsset kVfEmbeddedVfUiAssets[] = {\n")
set(index 0)
foreach(rel IN LISTS VF_UI_EMBEDDED_RELS)
  math(EXPR resource_id "${base_id} + ${index}")
  file(SIZE "${VF_UI_SOURCE_DIR}/${rel}" asset_size)
  string(REPLACE "\\" "\\\\" cpp_rel "${rel}")
  string(REPLACE "\"" "\\\"" cpp_rel "${cpp_rel}")
  string(APPEND cpp_text "    {${resource_id}, \"${cpp_rel}\", ${asset_size}ull},\n")
  math(EXPR index "${index} + 1")
endforeach()
string(APPEND cpp_text "};\nconst std::size_t kVfEmbeddedVfUiAssetCount = sizeof(kVfEmbeddedVfUiAssets) / sizeof(kVfEmbeddedVfUiAssets[0]);\n")
file(WRITE "${VF_UI_OUT_CPP}" "${cpp_text}")

list(LENGTH VF_UI_EMBEDDED_RELS asset_count)
message(STATUS "embedded ${asset_count} vf-ui assets, version ${vf_ui_version}")
