#!/usr/bin/env python3
import hashlib
import os
import sys
from pathlib import Path


def rc_escape(path: Path) -> str:
    return str(path).replace("\\", "\\\\").replace('"', '\\"')


def cpp_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if len(sys.argv) != 5:
        print(
            "usage: generate_embedded_vf_ui_assets.py <source_dir> <out_rc> <out_cpp> <out_hpp>",
            file=sys.stderr,
        )
        return 2

    source_dir = Path(sys.argv[1]).resolve()
    out_rc = Path(sys.argv[2]).resolve()
    out_cpp = Path(sys.argv[3]).resolve()
    out_hpp = Path(sys.argv[4]).resolve()
    if not source_dir.is_dir():
        print(f"source directory not found: {source_dir}", file=sys.stderr)
        return 1

    files = []
    for path in sorted(source_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(source_dir).as_posix()
        files.append((rel, path))

    digest = hashlib.sha256()
    for rel, path in files:
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    version = digest.hexdigest()[:24]

    out_rc.parent.mkdir(parents=True, exist_ok=True)
    out_cpp.parent.mkdir(parents=True, exist_ok=True)
    out_hpp.parent.mkdir(parents=True, exist_ok=True)

    base_id = 1000
    rc_lines = [
        "// Generated by generate_embedded_vf_ui_assets.py; do not edit.",
        "#include <windows.h>",
        "",
    ]
    for index, (_rel, path) in enumerate(files):
        rc_lines.append(f'{base_id + index} RCDATA "{rc_escape(path)}"')
    out_rc.write_text("\n".join(rc_lines) + "\n", encoding="utf-8")

    hpp = """#pragma once
#include <cstddef>

struct VfEmbeddedAsset {
    int resource_id;
    const char* relative_path;
    unsigned long long size;
};

extern const char* const kVfEmbeddedVfUiVersion;
extern const VfEmbeddedAsset kVfEmbeddedVfUiAssets[];
extern const std::size_t kVfEmbeddedVfUiAssetCount;
"""
    out_hpp.write_text(hpp, encoding="utf-8")

    cpp_lines = [
        "// Generated by generate_embedded_vf_ui_assets.py; do not edit.",
        '#include "embedded_vf_ui_assets.hpp"',
        "",
        f'const char* const kVfEmbeddedVfUiVersion = "{version}";',
        "const VfEmbeddedAsset kVfEmbeddedVfUiAssets[] = {",
    ]
    for index, (rel, path) in enumerate(files):
        size = path.stat().st_size
        cpp_lines.append(f'    {{{base_id + index}, "{cpp_escape(rel)}", {size}ull}},')
    cpp_lines.extend(
        [
            "};",
            "const std::size_t kVfEmbeddedVfUiAssetCount = sizeof(kVfEmbeddedVfUiAssets) / sizeof(kVfEmbeddedVfUiAssets[0]);",
            "",
        ]
    )
    out_cpp.write_text("\n".join(cpp_lines), encoding="utf-8")
    print(f"embedded {len(files)} vf-ui assets, version {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
